### ISSUE TITLE
SyntaxError: "undefined" is not valid JSON

### ISSUE THREAD

**Issue by devasafira** [AureliusIvan/remembear#53]
How to fix this error? Unsolved

Error on app\page.tsx line 151

![undefined error](https://github.com/user-attachments/assets/2e7d7c07-7bc8-4501-93cf-9366646af1ee)

**Comment by AureliusIvan** [comment]
You're right, the undefined value in data.data could be the issue. Would you like to try adding these lines to see if it resolves the problem?
`try {
            if (data && data.data) {
              return JSON.parse(data.data) as Chat[]
            }
            return []
          } catch (e) {
            console.error(e)
            return []
          }`
